from enum import StrEnum

from flyt.clients.provider import ProviderFailureClass

ERROR_CODE_MAX_LENGTH = 64
ERROR_MESSAGE_MAX_LENGTH = 500
FAILURE_CLASS_MAX_LENGTH = 64
UPSTREAM_IDENTIFIER_MAX_LENGTH = 255
PROVIDER_NAME_MAX_LENGTH = 32
MODEL_ID_MAX_LENGTH = 128
ANCHOR_MAX_LENGTH = 32
K_ESTIMATED_OUTPUT_TOKENS_PER_WORD = 3
K_GENERATE_STORY_JOB = "generate_story"


class StoryGenerationErrorCode(StrEnum):
    ALLOWANCE_EXHAUSTED = "STORY_GENERATION_ALLOWANCE_EXHAUSTED"
    AGGREGATE_CEILING_REACHED = "STORY_GENERATION_AGGREGATE_CEILING_REACHED"
    ANCHOR_NOTHING_TO_TEACH = "STORY_GENERATION_ANCHOR_NOTHING_TO_TEACH"
    TOPIC_TOO_LONG = "STORY_GENERATION_TOPIC_TOO_LONG"
    LENGTH_OUT_OF_RANGE = "STORY_GENERATION_LENGTH_OUT_OF_RANGE"
    PROVIDER_UNAVAILABLE = "STORY_GENERATION_PROVIDER_UNAVAILABLE"
    GENERATION_FAILED = "STORY_GENERATION_FAILED"
    GENERATION_ABANDONED = "STORY_GENERATION_ABANDONED"

    PROVIDER_AUTHENTICATION = "STORY_GENERATION_PROVIDER_AUTHENTICATION"
    PROVIDER_TIMEOUT = "STORY_GENERATION_PROVIDER_TIMEOUT"
    PROVIDER_REFUSAL = "STORY_GENERATION_PROVIDER_REFUSAL"
    PROVIDER_REQUEST_REJECTED = "STORY_GENERATION_PROVIDER_REQUEST_REJECTED"
    PROVIDER_MODEL_UNAVAILABLE = "STORY_GENERATION_PROVIDER_MODEL_UNAVAILABLE"
    PROVIDER_TRANSIENT = "STORY_GENERATION_PROVIDER_TRANSIENT"


_PROVIDER_FAILURE_CODE: dict[ProviderFailureClass, StoryGenerationErrorCode] = {
    ProviderFailureClass.AUTHENTICATION: StoryGenerationErrorCode.PROVIDER_AUTHENTICATION,
    ProviderFailureClass.TIMEOUT: StoryGenerationErrorCode.PROVIDER_TIMEOUT,
    ProviderFailureClass.UPSTREAM_REFUSAL: StoryGenerationErrorCode.PROVIDER_REFUSAL,
    ProviderFailureClass.REQUEST_REJECTED: StoryGenerationErrorCode.PROVIDER_REQUEST_REJECTED,
    ProviderFailureClass.MODEL_UNAVAILABLE: StoryGenerationErrorCode.PROVIDER_MODEL_UNAVAILABLE,
    ProviderFailureClass.TRANSIENT: StoryGenerationErrorCode.PROVIDER_TRANSIENT,
}


def provider_failure_code(
    failure_class: ProviderFailureClass,
) -> StoryGenerationErrorCode:
    return _PROVIDER_FAILURE_CODE[failure_class]
