"""add learner lemma context

Revision ID: 23ba9152c380
Revises: 944bb9a5ca8b
Create Date: 2026-09-05 21:24:54.811054

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23ba9152c380"
down_revision: str | Sequence[str] | None = "944bb9a5ca8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_lemma_contexts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lemma_id", sa.Integer(), nullable=False),
        sa.Column("source_sentence", sa.String(length=2000), nullable=False),
        sa.Column("source_title", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lemma_id"],
            ["lexicon_lemmas.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "lemma_id",
            "source_sentence",
            name="uq_user_lemma_context_source",
        ),
    )
    with op.batch_alter_table("user_lemma_contexts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_lemma_contexts_lemma_id"), ["lemma_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_lemma_contexts_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_lemma_contexts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_lemma_contexts_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_lemma_contexts_lemma_id"))

    op.drop_table("user_lemma_contexts")
    # ### end Alembic commands ###
