"""add lower form expression index on lexicon word forms

Revision ID: 24185d124c19
Revises: 7c3477c1d5a2
Create Date: 2026-08-08 13:51:13.015700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24185d124c19"
down_revision: Union[str, Sequence[str], None] = "7c3477c1d5a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lexicon_word_forms", schema=None) as batch_op:
        batch_op.create_index(
            "ix_lexicon_word_forms_form_lower",
            [sa.literal_column("lower(form)")],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lexicon_word_forms", schema=None) as batch_op:
        batch_op.drop_index("ix_lexicon_word_forms_form_lower")

    # ### end Alembic commands ###
