"""remove assistant key suffix

Revision ID: 32c8dd3ba435
Revises: 8eab6bcafaef
Create Date: 2026-08-30 00:46:09.879502

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32c8dd3ba435"
down_revision: str | Sequence[str] | None = "8eab6bcafaef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "assistant_openrouter_credentials", schema=None
    ) as batch_op:
        batch_op.drop_column("key_suffix")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "assistant_openrouter_credentials", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "key_suffix",
                sa.VARCHAR(length=4),
                autoincrement=False,
                nullable=True,
                server_default="????",
            )
        )
        batch_op.alter_column(
            "key_suffix",
            existing_type=sa.VARCHAR(length=4),
            nullable=False,
            server_default=None,
        )

    # ### end Alembic commands ###
