"""initial schema

Revision ID: 4004e0af8815
Revises:
Create Date: 2026-07-04 11:28:47.421610

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4004e0af8815"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flashcard_decks",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("license", sa.Text(), nullable=True),
        sa.Column("cefr_range", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lesson_sections",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "lexicon_lemmas",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("source_article_id", sa.Integer(), nullable=True),
        sa.Column("source_lemma_id", sa.Integer(), nullable=True),
        sa.Column("word", sa.String(), nullable=False),
        sa.Column(
            "pos",
            sa.Enum(
                "noun",
                "adjective",
                "verb",
                "adverb",
                "preposition",
                "conjunction",
                "pronoun",
                "determiner",
                "interjection",
                "numeral",
                "unknown",
                name="lemmapos",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("hgno", sa.Integer(), nullable=False),
        sa.Column("is_sub_article", sa.Boolean(), nullable=False),
        sa.Column("primary_translation", sa.Text(), nullable=True),
        sa.Column("cross_reference_article_id", sa.Integer(), nullable=True),
        sa.Column("cross_reference_word", sa.Text(), nullable=True),
        sa.Column("ipa", sa.Text(), nullable=True),
        sa.Column("intonation", sa.String(length=1), nullable=True),
        sa.Column(
            "ipa_approximate", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("audio_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_article_id", "word", "pos", "hgno"),
    )
    with op.batch_alter_table("lexicon_lemmas", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lexicon_lemmas_source_article_id"),
            ["source_article_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lexicon_lemmas_source_lemma_id"),
            ["source_lemma_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lexicon_lemmas_uuid"), ["uuid"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_lexicon_lemmas_word"), ["word"], unique=False
        )
        batch_op.create_index(
            "ix_lexicon_lemmas_word_pattern",
            ["word"],
            unique=False,
            postgresql_ops={"word": "varchar_pattern_ops"},
        )

    op.create_table(
        "reading_groups",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reading_groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reading_groups_key"), ["key"], unique=True)

    op.create_table(
        "user_users",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="userrole", native_enum=False),
            server_default="user",
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "lesson_chapters",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["lesson_sections.id"], name="fk_lesson_chapters_section_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    with op.batch_alter_table("lesson_chapters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lesson_chapters_section_id"), ["section_id"], unique=False
        )

    op.create_table(
        "lexicon_definitions",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("lemma_id", sa.Integer(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("translation", sa.Text(), nullable=False),
        sa.Column("translation_source", sa.String(), nullable=True),
        sa.Column("examples_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lemma_id"],
            ["lexicon_lemmas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lexicon_definitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lexicon_definitions_lemma_id"), ["lemma_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lexicon_definitions_uuid"), ["uuid"], unique=True
        )

    op.create_table(
        "lexicon_lemma_see_also",
        sa.Column("lemma_id", sa.Integer(), nullable=False),
        sa.Column("target_article_id", sa.Integer(), nullable=False),
        sa.Column("target_word", sa.Text(), nullable=False),
        sa.Column("relation", sa.String(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lemma_id"], ["lexicon_lemmas.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lexicon_lemma_see_also", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lexicon_lemma_see_also_lemma_id"), ["lemma_id"], unique=False
        )

    op.create_table(
        "lexicon_word_forms",
        sa.Column("lemma_id", sa.Integer(), nullable=False),
        sa.Column("form", sa.String(), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("ipa", sa.Text(), nullable=True),
        sa.Column("audio_url", sa.Text(), nullable=True),
        sa.Column(
            "ipa_approximate", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lemma_id"],
            ["lexicon_lemmas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lexicon_word_forms", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lexicon_word_forms_form"), ["form"], unique=False
        )
        batch_op.create_index(
            "ix_lexicon_word_forms_form_pattern",
            ["form"],
            unique=False,
            postgresql_ops={"form": "varchar_pattern_ops"},
        )
        batch_op.create_index(
            batch_op.f("ix_lexicon_word_forms_lemma_id"), ["lemma_id"], unique=False
        )

    op.create_table(
        "reading_stories",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("cefr_level", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("reading_group_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["reading_group_id"],
            ["reading_groups.id"],
            name="fk_reading_stories_reading_group_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reading_stories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reading_stories_cefr_level"), ["cefr_level"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reading_stories_is_published"),
            ["is_published"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_reading_stories_reading_group_id"),
            ["reading_group_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_reading_stories_slug"), ["slug"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_reading_stories_uuid"), ["uuid"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_reading_stories_word_count"), ["word_count"], unique=False
        )

    op.create_table(
        "user_auth_identities",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_subject", sa.String(length=255), nullable=False),
        sa.Column("email_at_link", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_subject"),
        sa.UniqueConstraint("user_id", "provider"),
    )
    with op.batch_alter_table("user_auth_identities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_auth_identities_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("daily_new_limit", sa.Integer(), server_default="20", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_settings_user_id"), ["user_id"], unique=True
        )

    op.create_table(
        "user_user_lemmas",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lemma_id", sa.Integer(), nullable=False),
        sa.Column("is_mastered", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lemma_id"],
            ["lexicon_lemmas.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "lemma_id"),
    )
    with op.batch_alter_table("user_user_lemmas", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_user_lemmas_lemma_id"), ["lemma_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_user_lemmas_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "lesson_lessons",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cefr_level", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(), nullable=True),
        sa.Column("elements_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"], ["lesson_chapters.id"], name="fk_lesson_lessons_chapter_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "key", name="uq_lesson_chapter_key"),
    )
    with op.batch_alter_table("lesson_lessons", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lesson_lessons_chapter_id"), ["chapter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lesson_lessons_order"), ["order"], unique=False
        )

    op.create_table(
        "reading_story_pages",
        sa.Column("story_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("text_annotations_json", sa.JSON(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["story_id"], ["reading_stories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("story_id", "index", name="uq_story_page_story_index"),
    )
    with op.batch_alter_table("reading_story_pages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reading_story_pages_story_id"), ["story_id"], unique=False
        )

    op.create_table(
        "user_stories",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("story_id", sa.Integer(), nullable=False),
        sa.Column("last_page_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["story_id"], ["reading_stories.id"], name="fk_user_stories_story_id"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_users.id"],
            name="fk_user_stories_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "story_id", name="uq_user_story_user_story"),
    )
    with op.batch_alter_table("user_stories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_stories_story_id"), ["story_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_stories_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "flashcard_card_pools",
        sa.Column("lesson_id", sa.Integer(), nullable=True),
        sa.Column("lemma_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("frequency_rank", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(lesson_id IS NULL) <> (lemma_id IS NULL)",
            name="ck_card_pool_exactly_one_owner",
        ),
        sa.ForeignKeyConstraint(
            ["lemma_id"], ["lexicon_lemmas.id"], name="fk_flashcard_card_pools_lemma_id"
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lesson_lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id", "key", name="uq_card_pool_lesson_key"),
    )
    with op.batch_alter_table("flashcard_card_pools", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_flashcard_card_pools_frequency_rank"),
            ["frequency_rank"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_flashcard_card_pools_lemma_id"), ["lemma_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_flashcard_card_pools_lesson_id"), ["lesson_id"], unique=False
        )

    op.create_table(
        "lesson_user_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("current_step_position", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lesson_lessons.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "lesson_id", name="uq_user_lesson_progress_user_lesson"
        ),
    )
    with op.batch_alter_table("lesson_user_progress", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lesson_user_progress_lesson_id"), ["lesson_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lesson_user_progress_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "flashcard_cards",
        sa.Column(
            "type",
            sa.Enum(
                "DEFINITION",
                "CLOZE",
                "ARRANGE",
                "INFO",
                "RECALL_FILL",
                "CHOOSE",
                "CATEGORIZE",
                "MATCH_PAIRS",
                "ORDER",
                "BUILD",
                "JUDGE",
                "FIND_FIX",
                name="cardtype",
            ),
            nullable=False,
        ),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.String(), nullable=True),
        sa.Column("is_addable", sa.Boolean(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=True),
        sa.Column("pool_id", sa.Integer(), nullable=True),
        sa.Column("uuid", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["flashcard_decks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"], ["flashcard_card_pools.id"], name="fk_flashcard_cards_pool_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    with op.batch_alter_table("flashcard_cards", schema=None) as batch_op:
        batch_op.create_index(
            "ix_flashcard_cards_deck_addable_pool",
            ["deck_id", "is_addable", "pool_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_flashcard_cards_deck_id"), ["deck_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_flashcard_cards_pool_id"), ["pool_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_flashcard_cards_type"), ["type"], unique=False
        )

    op.create_table(
        "flashcard_user_cards",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("last_shown_card_id", sa.Integer(), nullable=True),
        sa.Column("fsrs_stability", sa.Float(), nullable=True),
        sa.Column("fsrs_difficulty", sa.Float(), nullable=True),
        sa.Column("fsrs_step", sa.Integer(), nullable=True),
        sa.Column("last_review_at", sa.DateTime(), nullable=True),
        sa.Column("introduced_at", sa.DateTime(), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("NEW", "LEARNING", "REVIEW", "RELEARNING", name="cardstate"),
            nullable=False,
        ),
        sa.Column(
            "enrollment_state",
            sa.Enum("active", "upcoming", name="enrollment", native_enum=False),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["last_shown_card_id"],
            ["flashcard_cards.id"],
            name="fk_user_cards_last_shown_card_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"], ["flashcard_card_pools.id"], name="fk_user_cards_pool_id"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "pool_id", name="uq_user_card_pool"),
    )
    with op.batch_alter_table("flashcard_user_cards", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_flashcard_user_cards_due_at"), ["due_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_flashcard_user_cards_pool_id"), ["pool_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_flashcard_user_cards_state"), ["state"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_flashcard_user_cards_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_flashcard_user_cards_user_id_enrollment_state_state",
            ["user_id", "enrollment_state", "state"],
            unique=False,
        )
        batch_op.create_index(
            "ix_flashcard_user_cards_user_id_state", ["user_id", "state"], unique=False
        )

    op.create_table(
        "lesson_steps",
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["flashcard_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lesson_lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lesson_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lesson_steps_card_id"), ["card_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lesson_steps_lesson_id"), ["lesson_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lesson_steps_position"), ["position"], unique=False
        )

    op.create_table(
        "stats_review_logs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_card_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_card_id"],
            ["flashcard_user_cards.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stats_review_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_stats_review_logs_user_id_reviewed_at",
            ["user_id", "reviewed_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stats_review_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_stats_review_logs_user_id_reviewed_at")

    op.drop_table("stats_review_logs")
    with op.batch_alter_table("lesson_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lesson_steps_position"))
        batch_op.drop_index(batch_op.f("ix_lesson_steps_lesson_id"))
        batch_op.drop_index(batch_op.f("ix_lesson_steps_card_id"))

    op.drop_table("lesson_steps")
    with op.batch_alter_table("flashcard_user_cards", schema=None) as batch_op:
        batch_op.drop_index("ix_flashcard_user_cards_user_id_state")
        batch_op.drop_index("ix_flashcard_user_cards_user_id_enrollment_state_state")
        batch_op.drop_index(batch_op.f("ix_flashcard_user_cards_user_id"))
        batch_op.drop_index(batch_op.f("ix_flashcard_user_cards_state"))
        batch_op.drop_index(batch_op.f("ix_flashcard_user_cards_pool_id"))
        batch_op.drop_index(batch_op.f("ix_flashcard_user_cards_due_at"))

    op.drop_table("flashcard_user_cards")
    with op.batch_alter_table("flashcard_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flashcard_cards_type"))
        batch_op.drop_index(batch_op.f("ix_flashcard_cards_pool_id"))
        batch_op.drop_index(batch_op.f("ix_flashcard_cards_deck_id"))
        batch_op.drop_index("ix_flashcard_cards_deck_addable_pool")

    op.drop_table("flashcard_cards")
    with op.batch_alter_table("lesson_user_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lesson_user_progress_user_id"))
        batch_op.drop_index(batch_op.f("ix_lesson_user_progress_lesson_id"))

    op.drop_table("lesson_user_progress")
    with op.batch_alter_table("flashcard_card_pools", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flashcard_card_pools_lesson_id"))
        batch_op.drop_index(batch_op.f("ix_flashcard_card_pools_lemma_id"))
        batch_op.drop_index(batch_op.f("ix_flashcard_card_pools_frequency_rank"))

    op.drop_table("flashcard_card_pools")
    with op.batch_alter_table("user_stories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_stories_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_stories_story_id"))

    op.drop_table("user_stories")
    with op.batch_alter_table("reading_story_pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reading_story_pages_story_id"))

    op.drop_table("reading_story_pages")
    with op.batch_alter_table("lesson_lessons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lesson_lessons_order"))
        batch_op.drop_index(batch_op.f("ix_lesson_lessons_chapter_id"))

    op.drop_table("lesson_lessons")
    with op.batch_alter_table("user_user_lemmas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_user_lemmas_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_user_lemmas_lemma_id"))

    op.drop_table("user_user_lemmas")
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_settings_user_id"))

    op.drop_table("user_settings")
    with op.batch_alter_table("user_auth_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_auth_identities_user_id"))

    op.drop_table("user_auth_identities")
    with op.batch_alter_table("reading_stories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reading_stories_word_count"))
        batch_op.drop_index(batch_op.f("ix_reading_stories_uuid"))
        batch_op.drop_index(batch_op.f("ix_reading_stories_slug"))
        batch_op.drop_index(batch_op.f("ix_reading_stories_reading_group_id"))
        batch_op.drop_index(batch_op.f("ix_reading_stories_is_published"))
        batch_op.drop_index(batch_op.f("ix_reading_stories_cefr_level"))

    op.drop_table("reading_stories")
    with op.batch_alter_table("lexicon_word_forms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lexicon_word_forms_lemma_id"))
        batch_op.drop_index(
            "ix_lexicon_word_forms_form_pattern",
            postgresql_ops={"form": "varchar_pattern_ops"},
        )
        batch_op.drop_index(batch_op.f("ix_lexicon_word_forms_form"))

    op.drop_table("lexicon_word_forms")
    with op.batch_alter_table("lexicon_lemma_see_also", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lexicon_lemma_see_also_lemma_id"))

    op.drop_table("lexicon_lemma_see_also")
    with op.batch_alter_table("lexicon_definitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lexicon_definitions_uuid"))
        batch_op.drop_index(batch_op.f("ix_lexicon_definitions_lemma_id"))

    op.drop_table("lexicon_definitions")
    with op.batch_alter_table("lesson_chapters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lesson_chapters_section_id"))

    op.drop_table("lesson_chapters")
    op.drop_table("user_users")
    with op.batch_alter_table("reading_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reading_groups_key"))

    op.drop_table("reading_groups")
    with op.batch_alter_table("lexicon_lemmas", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_lexicon_lemmas_word_pattern",
            postgresql_ops={"word": "varchar_pattern_ops"},
        )
        batch_op.drop_index(batch_op.f("ix_lexicon_lemmas_word"))
        batch_op.drop_index(batch_op.f("ix_lexicon_lemmas_uuid"))
        batch_op.drop_index(batch_op.f("ix_lexicon_lemmas_source_lemma_id"))
        batch_op.drop_index(batch_op.f("ix_lexicon_lemmas_source_article_id"))

    op.drop_table("lexicon_lemmas")
    op.drop_table("lesson_sections")
    op.drop_table("flashcard_decks")
    # ### end Alembic commands ###
