"""chatgpt link

Revision ID: 6586d79553b2
Revises: a0792c849497
Create Date: 2026-07-26 11:04:35.774745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6586d79553b2"
down_revision: Union[str, Sequence[str], None] = "a0792c849497"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatgpt_link",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("chatgpt_account_id", sa.String(), nullable=False),
        sa.Column("access_token_expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("working", "broken", name="chatgptlinkstate", native_enum=False),
            server_default="working",
            nullable=False,
        ),
        sa.Column("broken_reason", sa.String(), nullable=True),
        sa.Column("model_key", sa.String(), nullable=True),
        sa.Column("last_refresh_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chatgpt_link", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chatgpt_link_user_id"), ["user_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chatgpt_link", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chatgpt_link_user_id"))

    op.drop_table("chatgpt_link")
    # ### end Alembic commands ###
