"""measure story generation composition

Revision ID: 77ecbb7ecc41
Revises: ae397c1f85ce
Create Date: 2026-08-10 23:45:08.254666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77ecbb7ecc41"
down_revision: Union[str, Sequence[str], None] = "ae397c1f85ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("story_generation_generations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("mastered_lemma_count", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("in_progress_lemma_count", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("unknown_lemma_count", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("mastered_token_count", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("in_progress_token_count", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("unknown_token_count", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("lexical_token_count", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("target_occurrences", sa.JSON(), nullable=True))
        batch_op.drop_column("mastered_count")
        batch_op.drop_column("in_progress_count")
        batch_op.drop_column("unknown_count")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("story_generation_generations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("unknown_count", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "in_progress_count", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "mastered_count", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_column("target_occurrences")
        batch_op.drop_column("lexical_token_count")
        batch_op.drop_column("unknown_token_count")
        batch_op.drop_column("in_progress_token_count")
        batch_op.drop_column("mastered_token_count")
        batch_op.drop_column("unknown_lemma_count")
        batch_op.drop_column("in_progress_lemma_count")
        batch_op.drop_column("mastered_lemma_count")

    # ### end Alembic commands ###
