"""migrate lessons to export v4

Revision ID: 77f9cb489d5b
Revises: fd8727d54580
Create Date: 2026-08-17 10:44:40.567266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "77f9cb489d5b"
down_revision: Union[str, Sequence[str], None] = "fd8727d54580"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The initial schema created a native enum before v4 added speak/write.
    op.execute("ALTER TYPE cardtype ADD VALUE IF NOT EXISTS 'SPEAK'")
    op.execute("ALTER TYPE cardtype ADD VALUE IF NOT EXISTS 'WRITE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lesson_releases",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("schema_version", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("translation_language", sa.String(), nullable=False),
        sa.Column("lesson_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest"),
    )
    with op.batch_alter_table("lesson_releases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lesson_releases_is_active"), ["is_active"], unique=False
        )

    with op.batch_alter_table("lesson_lessons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("release_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("source_id", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("release_order", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("kind", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("family_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("goal", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("packet_json", sa.JSON(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_lesson_lessons_chapter_id"))
        batch_op.drop_index(batch_op.f("ix_lesson_lessons_order"))
        batch_op.drop_constraint(batch_op.f("uq_lesson_chapter_key"), type_="unique")
        batch_op.create_index(
            batch_op.f("ix_lesson_lessons_release_id"), ["release_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lesson_lessons_release_order"),
            ["release_order"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "uq_lesson_release_source_id", ["release_id", "source_id"]
        )
        batch_op.drop_constraint(
            batch_op.f("fk_lesson_lessons_chapter_id"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_lesson_lessons_release_id", "lesson_releases", ["release_id"], ["id"]
        )
        batch_op.drop_column("schema_version")
        batch_op.drop_column("key")
        batch_op.drop_column("description")
        batch_op.drop_column("chapter_id")
        batch_op.drop_column("elements_json")
        batch_op.drop_column("order")

    with op.batch_alter_table("lesson_user_progress", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("completed_exercise_ids_json", sa.JSON(), nullable=False)
        )
        batch_op.drop_column("current_step_position")

    with op.batch_alter_table("lesson_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lesson_steps_card_id"))
        batch_op.drop_index(batch_op.f("ix_lesson_steps_lesson_id"))
        batch_op.drop_index(batch_op.f("ix_lesson_steps_position"))

    op.drop_table("lesson_steps")
    with op.batch_alter_table("lesson_chapters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lesson_chapters_section_id"))

    op.drop_table("lesson_chapters")
    op.drop_table("lesson_sections")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson_user_progress", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "current_step_position",
                sa.INTEGER(),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("completed_exercise_ids_json")

    op.create_table(
        "lesson_sections",
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("lesson_sections_pkey")),
        sa.UniqueConstraint(
            "key",
            name=op.f("lesson_sections_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "lesson_steps",
        sa.Column("lesson_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("card_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["card_id"], ["flashcard_cards.id"], name=op.f("lesson_steps_card_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lesson_lessons.id"],
            name=op.f("lesson_steps_lesson_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("lesson_steps_pkey")),
    )
    with op.batch_alter_table("lesson_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lesson_steps_position"), ["position"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lesson_steps_lesson_id"), ["lesson_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lesson_steps_card_id"), ["card_id"], unique=False
        )

    op.create_table(
        "lesson_chapters",
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("section_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["lesson_sections.id"],
            name=op.f("fk_lesson_chapters_section_id"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("lesson_chapters_pkey")),
        sa.UniqueConstraint(
            "key",
            name=op.f("lesson_chapters_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    with op.batch_alter_table("lesson_chapters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lesson_chapters_section_id"), ["section_id"], unique=False
        )

    with op.batch_alter_table("lesson_lessons", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "elements_json",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("chapter_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "schema_version", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_constraint("fk_lesson_lessons_release_id", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_lesson_lessons_chapter_id"),
            "lesson_chapters",
            ["chapter_id"],
            ["id"],
        )
        batch_op.drop_constraint("uq_lesson_release_source_id", type_="unique")
        batch_op.drop_index(batch_op.f("ix_lesson_lessons_release_order"))
        batch_op.drop_index(batch_op.f("ix_lesson_lessons_release_id"))
        batch_op.create_unique_constraint(
            batch_op.f("uq_lesson_chapter_key"),
            ["chapter_id", "key"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lesson_lessons_order"), ["order"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lesson_lessons_chapter_id"), ["chapter_id"], unique=False
        )
        batch_op.drop_column("packet_json")
        batch_op.drop_column("goal")
        batch_op.drop_column("family_id")
        batch_op.drop_column("kind")
        batch_op.drop_column("release_order")
        batch_op.drop_column("source_id")
        batch_op.drop_column("release_id")

    with op.batch_alter_table("lesson_releases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lesson_releases_is_active"))

    op.drop_table("lesson_releases")
    # ### end Alembic commands ###
