"""add assistant credentials and usage

Revision ID: 8eab6bcafaef
Revises: 77f9cb489d5b
Create Date: 2026-08-29 21:54:34.092007

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8eab6bcafaef"
down_revision: str | Sequence[str] | None = "77f9cb489d5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_openrouter_credentials",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("api_key", sa.Text(), nullable=False),
        sa.Column("key_suffix", sa.String(length=4), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_users.id"],
            name="fk_assistant_openrouter_credentials_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "assistant_openrouter_credentials", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assistant_openrouter_credentials_user_id"),
            ["user_id"],
            unique=True,
        )

    op.create_table(
        "assistant_usage",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("message_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_users.id"],
            name="fk_assistant_usage_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "period_start", name="uq_assistant_usage_user_period"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assistant_usage")
    with op.batch_alter_table(
        "assistant_openrouter_credentials", schema=None
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assistant_openrouter_credentials_user_id"))

    op.drop_table("assistant_openrouter_credentials")
    # ### end Alembic commands ###
