"""add story_import_quota lifetime counter

Revision ID: a0792c849497
Revises: d46ada0291aa
Create Date: 2026-07-24 05:49:44.703313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0792c849497"
down_revision: Union[str, Sequence[str], None] = "d46ada0291aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story_import_quota",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_users.id"],
            name="fk_story_import_quota_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("story_import_quota", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_story_import_quota_user_id"), ["user_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("story_import_quota", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_story_import_quota_user_id"))

    op.drop_table("story_import_quota")
    # ### end Alembic commands ###
