"""add story generation records

Revision ID: ae397c1f85ce
Revises: 24185d124c19
Create Date: 2026-08-10 11:03:39.640068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae397c1f85ce"
down_revision: Union[str, Sequence[str], None] = "24185d124c19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story_generation_generations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("anchor", sa.String(length=32), nullable=True),
        sa.Column("requested_length", sa.Integer(), nullable=True),
        sa.Column("requested_targets", sa.Integer(), nullable=True),
        sa.Column("mastered_count", sa.Integer(), nullable=True),
        sa.Column("in_progress_count", sa.Integer(), nullable=True),
        sa.Column("unknown_count", sa.Integer(), nullable=True),
        sa.Column("unresolved_token_rate", sa.Float(), nullable=True),
        sa.Column("produced_length", sa.Integer(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "ready",
                "failed",
                "refused",
                name="generationoutcome",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_users.id"],
            name="fk_story_generation_generations_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("story_generation_generations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_story_generation_generations_outcome"),
            ["outcome"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_story_generation_generations_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "story_generation_provider_requests",
        sa.Column("generation_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "success", "failure", name="providerrequestoutcome", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("failure_class", sa.String(length=64), nullable=True),
        sa.Column("upstream_identifier", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["story_generation_generations.id"],
            name="fk_story_generation_provider_requests_generation_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "story_generation_provider_requests", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_story_generation_provider_requests_generation_id"),
            ["generation_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "story_generation_provider_requests", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_story_generation_provider_requests_generation_id")
        )

    op.drop_table("story_generation_provider_requests")
    with op.batch_alter_table("story_generation_generations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_story_generation_generations_user_id"))
        batch_op.drop_index(batch_op.f("ix_story_generation_generations_outcome"))

    op.drop_table("story_generation_generations")
    # ### end Alembic commands ###
