"""add story import (private stories, inline content)

Revision ID: d46ada0291aa
Revises: b2c3d4e5f6a7
Create Date: 2026-07-21 07:23:43.157167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d46ada0291aa"
down_revision: Union[str, Sequence[str], None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("public", "private", name="storyvisibility").create(
        op.get_bind(), checkfirst=True
    )
    op.create_table(
        "import_meta",
        sa.Column("story_id", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "READY", "FAILED", name="importstatus"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["reading_stories.id"],
            name="fk_import_meta_story_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("story_id"),
    )
    with op.batch_alter_table("import_meta", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_import_meta_content_hash"), ["content_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_import_meta_status"), ["status"], unique=False
        )

    with op.batch_alter_table("reading_stories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "visibility",
                sa.Enum("public", "private", name="storyvisibility"),
                server_default="private",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("is_ready", sa.Boolean(), server_default="false", nullable=False)
        )
        batch_op.alter_column("content", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("cefr_level", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("slug", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "reading_group_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.drop_index(batch_op.f("ix_reading_stories_is_published"))
        batch_op.create_index(
            batch_op.f("ix_reading_stories_is_ready"), ["is_ready"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reading_stories_visibility"), ["visibility"], unique=False
        )
        batch_op.drop_column("is_published")

    with op.batch_alter_table("reading_story_pages", schema=None) as batch_op:
        batch_op.alter_column(
            "text_annotations_json",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        )

    with op.batch_alter_table("user_stories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("title", sa.String(length=200), nullable=True))
        batch_op.add_column(
            sa.Column("source_url", sa.String(length=2048), nullable=True)
        )
        batch_op.create_index(batch_op.f("ix_user_stories_uuid"), ["uuid"], unique=True)
        batch_op.drop_constraint(
            batch_op.f("fk_user_stories_story_id"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_user_stories_story_id",
            "reading_stories",
            ["story_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # Backfill uuid for any pre-existing rows, then enforce NOT NULL.
    op.execute("UPDATE user_stories SET uuid = gen_random_uuid() WHERE uuid IS NULL")
    with op.batch_alter_table("user_stories", schema=None) as batch_op:
        batch_op.alter_column("uuid", existing_type=sa.Uuid(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_stories", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_stories_story_id", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_user_stories_story_id"),
            "reading_stories",
            ["story_id"],
            ["id"],
        )
        batch_op.drop_index(batch_op.f("ix_user_stories_uuid"))
        batch_op.drop_column("source_url")
        batch_op.drop_column("title")
        batch_op.drop_column("uuid")

    with op.batch_alter_table("reading_story_pages", schema=None) as batch_op:
        batch_op.alter_column(
            "text_annotations_json",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
        )

    with op.batch_alter_table("reading_stories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_published",
                sa.BOOLEAN(),
                server_default=sa.text("false"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_index(batch_op.f("ix_reading_stories_visibility"))
        batch_op.drop_index(batch_op.f("ix_reading_stories_is_ready"))
        batch_op.create_index(
            batch_op.f("ix_reading_stories_is_published"),
            ["is_published"],
            unique=False,
        )
        batch_op.alter_column(
            "reading_group_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("slug", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("cefr_level", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("content", existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column("is_ready")
        batch_op.drop_column("visibility")

    with op.batch_alter_table("import_meta", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_meta_status"))
        batch_op.drop_index(batch_op.f("ix_import_meta_content_hash"))

    op.drop_table("import_meta")
    sa.Enum(name="importstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="storyvisibility").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
