"""track active review issuance

Revision ID: d99bf55371a5
Revises: 23ba9152c380
Create Date: 2026-09-08 04:57:20.494175

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d99bf55371a5"
down_revision: str | Sequence[str] | None = "23ba9152c380"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flashcard_user_cards", schema=None) as batch_op:
        batch_op.add_column(sa.Column("active_card_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_flashcard_user_cards_active_card_id"),
            ["active_card_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_user_cards_active_card_id",
            "flashcard_cards",
            ["active_card_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flashcard_user_cards", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_cards_active_card_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_flashcard_user_cards_active_card_id"))
        batch_op.drop_column("active_card_id")

    # ### end Alembic commands ###
