"""add expression aliases

Revision ID: e1c0ffa70688
Revises: d99bf55371a5
Create Date: 2026-09-09 08:41:05.371451

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1c0ffa70688"
down_revision: str | Sequence[str] | None = "d99bf55371a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lexicon_lemma_aliases",
        sa.Column("lemma_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=80), nullable=False),
        sa.Column("normalized_alias", sa.String(length=80), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lemma_id"], ["lexicon_lemmas.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "lemma_id",
            "normalized_alias",
            name="uq_lexicon_lemma_alias_lemma_normalized",
        ),
    )
    with op.batch_alter_table("lexicon_lemma_aliases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lexicon_lemma_aliases_lemma_id"), ["lemma_id"], unique=False
        )
        batch_op.create_index(
            "ix_lexicon_lemma_aliases_normalized_exact",
            ["normalized_alias"],
            unique=False,
        )
        batch_op.create_index(
            "ix_lexicon_lemma_aliases_normalized_pattern",
            ["normalized_alias"],
            unique=False,
            postgresql_ops={"normalized_alias": "varchar_pattern_ops"},
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lexicon_lemma_aliases", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_lexicon_lemma_aliases_normalized_pattern",
            postgresql_ops={"normalized_alias": "varchar_pattern_ops"},
        )
        batch_op.drop_index("ix_lexicon_lemma_aliases_normalized_exact")
        batch_op.drop_index(batch_op.f("ix_lexicon_lemma_aliases_lemma_id"))

    op.drop_table("lexicon_lemma_aliases")
    # ### end Alembic commands ###
