"""add processing outcome to story generations

Revision ID: fd8727d54580
Revises: 77ecbb7ecc41
Create Date: 2026-08-11 03:50:57.517532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd8727d54580"
down_revision: Union[str, Sequence[str], None] = "77ecbb7ecc41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("story_generation_generations", schema=None) as batch_op:
        batch_op.alter_column(
            "outcome",
            existing_type=sa.VARCHAR(length=7),
            type_=sa.Enum(
                "processing",
                "ready",
                "failed",
                "refused",
                name="generationoutcome",
                native_enum=False,
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("story_generation_generations", schema=None) as batch_op:
        batch_op.alter_column(
            "outcome",
            existing_type=sa.Enum(
                "processing",
                "ready",
                "failed",
                "refused",
                name="generationoutcome",
                native_enum=False,
            ),
            type_=sa.VARCHAR(length=7),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
