from datetime import timedelta

CONTENT_HASH_LENGTH = 64
DERIVED_TITLE_WORDS = 10
ERROR_CODE_MAX_LENGTH = 64
ERROR_CODE_PROCESSING_FAILED = "PROCESSING_FAILED"
ERROR_MESSAGE_MAX_LENGTH = 500
IMPORT_LIMIT = 200
MAX_NORMALIZED_BYTES = 100_000
PROCESS_IMPORT_JOB = "process_import"
SOURCE_URL_MAX_LENGTH = 2048
STALE_AFTER = timedelta(hours=1)
TITLE_MAX_LENGTH = 200

DEFAULT_PAGE_LIMIT = IMPORT_LIMIT
MAX_PAGE_LIMIT = IMPORT_LIMIT
