/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonSessionRouteImport } from './routes/_lessonSession'
import { Route as ReaderRouteImport } from './routes/_reader'
import { Route as ReadingThemeRouteImport } from './routes/_readingTheme'
import { Route as ReviewCardsRouteImport } from './routes/_reviewCards'
import { Route as ReviewSessionRouteImport } from './routes/_reviewSession'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WordsRouteImport } from './routes/words'
import { Route as ShellAccountRouteImport } from './routes/_shell.account'
import { Route as ShellHomeRouteImport } from './routes/_shell.home'
import { Route as ShellLessonRouteImport } from './routes/_shell.lesson'
import { Route as ShellReadingRouteImport } from './routes/_shell.reading'
import { Route as ShellReviewRouteImport } from './routes/_shell.review'
import { Route as ShellSearchRouteImport } from './routes/_shell.search'
import { Route as LessonSessionLessonLessonIdRouteImport } from './routes/_lessonSession.lesson.$lessonId'
import { Route as ReviewCardsReviewCardsRouteImport } from './routes/_reviewCards.review.cards'
import { Route as ReviewSessionReviewSessionRouteImport } from './routes/_reviewSession.review.session'
import { Route as ShellLessonIndexRouteImport } from './routes/_shell.lesson.index'
import { Route as ShellReadingIndexRouteImport } from './routes/_shell.reading.index'
import { Route as ShellReadingGenerateRouteImport } from './routes/_shell.reading.generate'
import { Route as ShellReadingImportsRouteImport } from './routes/_shell.reading.imports'
import { Route as ShellReviewIndexRouteImport } from './routes/_shell.review.index'
import { Route as ShellReviewPickRouteImport } from './routes/_shell.review.pick'
import { Route as ReaderReadingStoryUuidRouteImport } from './routes/_reader.reading.story.$uuid'
import { Route as ReadingThemeReadingThemesKeyRouteImport } from './routes/_readingTheme.reading.themes.$key'
import { Route as ShellReadingImportsInstallRouteImport } from './routes/_shell.reading.imports_.install'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonSessionRoute = LessonSessionRouteImport.update({
  id: '/_lessonSession',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/_reader',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingThemeRoute = ReadingThemeRouteImport.update({
  id: '/_readingTheme',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewCardsRoute = ReviewCardsRouteImport.update({
  id: '/_reviewCards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSessionRoute = ReviewSessionRouteImport.update({
  id: '/_reviewSession',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsRoute = WordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAccountRoute = ShellAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeRoute = ShellHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLessonRoute = ShellLessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReadingRoute = ShellReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReviewRoute = ShellReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSearchRoute = ShellSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShellRoute,
} as any)
const LessonSessionLessonLessonIdRoute =
  LessonSessionLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => LessonSessionRoute,
  } as any)
const ReviewCardsReviewCardsRoute = ReviewCardsReviewCardsRouteImport.update({
  id: '/review/cards',
  path: '/review/cards',
  getParentRoute: () => ReviewCardsRoute,
} as any)
const ReviewSessionReviewSessionRoute =
  ReviewSessionReviewSessionRouteImport.update({
    id: '/review/session',
    path: '/review/session',
    getParentRoute: () => ReviewSessionRoute,
  } as any)
const ShellLessonIndexRoute = ShellLessonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellLessonRoute,
} as any)
const ShellReadingIndexRoute = ShellReadingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellReadingRoute,
} as any)
const ShellReadingGenerateRoute = ShellReadingGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => ShellReadingRoute,
} as any)
const ShellReadingImportsRoute = ShellReadingImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => ShellReadingRoute,
} as any)
const ShellReviewIndexRoute = ShellReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellReviewRoute,
} as any)
const ShellReviewPickRoute = ShellReviewPickRouteImport.update({
  id: '/pick',
  path: '/pick',
  getParentRoute: () => ShellReviewRoute,
} as any)
const ReaderReadingStoryUuidRoute = ReaderReadingStoryUuidRouteImport.update({
  id: '/reading/story/$uuid',
  path: '/reading/story/$uuid',
  getParentRoute: () => ReaderRoute,
} as any)
const ReadingThemeReadingThemesKeyRoute =
  ReadingThemeReadingThemesKeyRouteImport.update({
    id: '/reading/themes/$key',
    path: '/reading/themes/$key',
    getParentRoute: () => ReadingThemeRoute,
  } as any)
const ShellReadingImportsInstallRoute =
  ShellReadingImportsInstallRouteImport.update({
    id: '/imports_/install',
    path: '/imports/install',
    getParentRoute: () => ShellReadingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/words': typeof WordsRoute
  '/account': typeof ShellAccountRoute
  '/home': typeof ShellHomeRoute
  '/lesson': typeof ShellLessonRouteWithChildren
  '/reading': typeof ShellReadingRouteWithChildren
  '/review': typeof ShellReviewRouteWithChildren
  '/search': typeof ShellSearchRoute
  '/lesson/$lessonId': typeof LessonSessionLessonLessonIdRoute
  '/review/cards': typeof ReviewCardsReviewCardsRoute
  '/review/session': typeof ReviewSessionReviewSessionRoute
  '/reading/generate': typeof ShellReadingGenerateRoute
  '/reading/imports': typeof ShellReadingImportsRoute
  '/review/pick': typeof ShellReviewPickRoute
  '/lesson/': typeof ShellLessonIndexRoute
  '/reading/': typeof ShellReadingIndexRoute
  '/review/': typeof ShellReviewIndexRoute
  '/reading/story/$uuid': typeof ReaderReadingStoryUuidRoute
  '/reading/themes/$key': typeof ReadingThemeReadingThemesKeyRoute
  '/reading/imports/install': typeof ShellReadingImportsInstallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/words': typeof WordsRoute
  '/account': typeof ShellAccountRoute
  '/home': typeof ShellHomeRoute
  '/search': typeof ShellSearchRoute
  '/lesson/$lessonId': typeof LessonSessionLessonLessonIdRoute
  '/review/cards': typeof ReviewCardsReviewCardsRoute
  '/review/session': typeof ReviewSessionReviewSessionRoute
  '/reading/generate': typeof ShellReadingGenerateRoute
  '/reading/imports': typeof ShellReadingImportsRoute
  '/review/pick': typeof ShellReviewPickRoute
  '/lesson': typeof ShellLessonIndexRoute
  '/reading': typeof ShellReadingIndexRoute
  '/review': typeof ShellReviewIndexRoute
  '/reading/story/$uuid': typeof ReaderReadingStoryUuidRoute
  '/reading/themes/$key': typeof ReadingThemeReadingThemesKeyRoute
  '/reading/imports/install': typeof ShellReadingImportsInstallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_lessonSession': typeof LessonSessionRouteWithChildren
  '/_reader': typeof ReaderRouteWithChildren
  '/_readingTheme': typeof ReadingThemeRouteWithChildren
  '/_reviewCards': typeof ReviewCardsRouteWithChildren
  '/_reviewSession': typeof ReviewSessionRouteWithChildren
  '/_shell': typeof ShellRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/words': typeof WordsRoute
  '/_shell/account': typeof ShellAccountRoute
  '/_shell/home': typeof ShellHomeRoute
  '/_shell/lesson': typeof ShellLessonRouteWithChildren
  '/_shell/reading': typeof ShellReadingRouteWithChildren
  '/_shell/review': typeof ShellReviewRouteWithChildren
  '/_shell/search': typeof ShellSearchRoute
  '/_lessonSession/lesson/$lessonId': typeof LessonSessionLessonLessonIdRoute
  '/_reviewCards/review/cards': typeof ReviewCardsReviewCardsRoute
  '/_reviewSession/review/session': typeof ReviewSessionReviewSessionRoute
  '/_shell/reading/generate': typeof ShellReadingGenerateRoute
  '/_shell/reading/imports': typeof ShellReadingImportsRoute
  '/_shell/review/pick': typeof ShellReviewPickRoute
  '/_shell/lesson/': typeof ShellLessonIndexRoute
  '/_shell/reading/': typeof ShellReadingIndexRoute
  '/_shell/review/': typeof ShellReviewIndexRoute
  '/_reader/reading/story/$uuid': typeof ReaderReadingStoryUuidRoute
  '/_readingTheme/reading/themes/$key': typeof ReadingThemeReadingThemesKeyRoute
  '/_shell/reading/imports_/install': typeof ShellReadingImportsInstallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/words'
    | '/account'
    | '/home'
    | '/lesson'
    | '/reading'
    | '/review'
    | '/search'
    | '/lesson/$lessonId'
    | '/review/cards'
    | '/review/session'
    | '/reading/generate'
    | '/reading/imports'
    | '/review/pick'
    | '/lesson/'
    | '/reading/'
    | '/review/'
    | '/reading/story/$uuid'
    | '/reading/themes/$key'
    | '/reading/imports/install'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/words'
    | '/account'
    | '/home'
    | '/search'
    | '/lesson/$lessonId'
    | '/review/cards'
    | '/review/session'
    | '/reading/generate'
    | '/reading/imports'
    | '/review/pick'
    | '/lesson'
    | '/reading'
    | '/review'
    | '/reading/story/$uuid'
    | '/reading/themes/$key'
    | '/reading/imports/install'
  id:
    | '__root__'
    | '/'
    | '/_lessonSession'
    | '/_reader'
    | '/_readingTheme'
    | '/_reviewCards'
    | '/_reviewSession'
    | '/_shell'
    | '/about'
    | '/login'
    | '/words'
    | '/_shell/account'
    | '/_shell/home'
    | '/_shell/lesson'
    | '/_shell/reading'
    | '/_shell/review'
    | '/_shell/search'
    | '/_lessonSession/lesson/$lessonId'
    | '/_reviewCards/review/cards'
    | '/_reviewSession/review/session'
    | '/_shell/reading/generate'
    | '/_shell/reading/imports'
    | '/_shell/review/pick'
    | '/_shell/lesson/'
    | '/_shell/reading/'
    | '/_shell/review/'
    | '/_reader/reading/story/$uuid'
    | '/_readingTheme/reading/themes/$key'
    | '/_shell/reading/imports_/install'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonSessionRoute: typeof LessonSessionRouteWithChildren
  ReaderRoute: typeof ReaderRouteWithChildren
  ReadingThemeRoute: typeof ReadingThemeRouteWithChildren
  ReviewCardsRoute: typeof ReviewCardsRouteWithChildren
  ReviewSessionRoute: typeof ReviewSessionRouteWithChildren
  ShellRoute: typeof ShellRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  WordsRoute: typeof WordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lessonSession': {
      id: '/_lessonSession'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LessonSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reader': {
      id: '/_reader'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_readingTheme': {
      id: '/_readingTheme'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ReadingThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reviewCards': {
      id: '/_reviewCards'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ReviewCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reviewSession': {
      id: '/_reviewSession'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ReviewSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/account': {
      id: '/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShellAccountRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/home': {
      id: '/_shell/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ShellHomeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/lesson': {
      id: '/_shell/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof ShellLessonRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reading': {
      id: '/_shell/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ShellReadingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/review': {
      id: '/_shell/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ShellReviewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/search': {
      id: '/_shell/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShellSearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_lessonSession/lesson/$lessonId': {
      id: '/_lessonSession/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonSessionLessonLessonIdRouteImport
      parentRoute: typeof LessonSessionRoute
    }
    '/_reviewCards/review/cards': {
      id: '/_reviewCards/review/cards'
      path: '/review/cards'
      fullPath: '/review/cards'
      preLoaderRoute: typeof ReviewCardsReviewCardsRouteImport
      parentRoute: typeof ReviewCardsRoute
    }
    '/_reviewSession/review/session': {
      id: '/_reviewSession/review/session'
      path: '/review/session'
      fullPath: '/review/session'
      preLoaderRoute: typeof ReviewSessionReviewSessionRouteImport
      parentRoute: typeof ReviewSessionRoute
    }
    '/_shell/lesson/': {
      id: '/_shell/lesson/'
      path: '/'
      fullPath: '/lesson/'
      preLoaderRoute: typeof ShellLessonIndexRouteImport
      parentRoute: typeof ShellLessonRoute
    }
    '/_shell/reading/': {
      id: '/_shell/reading/'
      path: '/'
      fullPath: '/reading/'
      preLoaderRoute: typeof ShellReadingIndexRouteImport
      parentRoute: typeof ShellReadingRoute
    }
    '/_shell/reading/generate': {
      id: '/_shell/reading/generate'
      path: '/generate'
      fullPath: '/reading/generate'
      preLoaderRoute: typeof ShellReadingGenerateRouteImport
      parentRoute: typeof ShellReadingRoute
    }
    '/_shell/reading/imports': {
      id: '/_shell/reading/imports'
      path: '/imports'
      fullPath: '/reading/imports'
      preLoaderRoute: typeof ShellReadingImportsRouteImport
      parentRoute: typeof ShellReadingRoute
    }
    '/_shell/review/': {
      id: '/_shell/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ShellReviewIndexRouteImport
      parentRoute: typeof ShellReviewRoute
    }
    '/_shell/review/pick': {
      id: '/_shell/review/pick'
      path: '/pick'
      fullPath: '/review/pick'
      preLoaderRoute: typeof ShellReviewPickRouteImport
      parentRoute: typeof ShellReviewRoute
    }
    '/_reader/reading/story/$uuid': {
      id: '/_reader/reading/story/$uuid'
      path: '/reading/story/$uuid'
      fullPath: '/reading/story/$uuid'
      preLoaderRoute: typeof ReaderReadingStoryUuidRouteImport
      parentRoute: typeof ReaderRoute
    }
    '/_readingTheme/reading/themes/$key': {
      id: '/_readingTheme/reading/themes/$key'
      path: '/reading/themes/$key'
      fullPath: '/reading/themes/$key'
      preLoaderRoute: typeof ReadingThemeReadingThemesKeyRouteImport
      parentRoute: typeof ReadingThemeRoute
    }
    '/_shell/reading/imports_/install': {
      id: '/_shell/reading/imports_/install'
      path: '/imports/install'
      fullPath: '/reading/imports/install'
      preLoaderRoute: typeof ShellReadingImportsInstallRouteImport
      parentRoute: typeof ShellReadingRoute
    }
  }
}

interface LessonSessionRouteChildren {
  LessonSessionLessonLessonIdRoute: typeof LessonSessionLessonLessonIdRoute
}

const LessonSessionRouteChildren: LessonSessionRouteChildren = {
  LessonSessionLessonLessonIdRoute: LessonSessionLessonLessonIdRoute,
}

const LessonSessionRouteWithChildren = LessonSessionRoute._addFileChildren(
  LessonSessionRouteChildren,
)

interface ReaderRouteChildren {
  ReaderReadingStoryUuidRoute: typeof ReaderReadingStoryUuidRoute
}

const ReaderRouteChildren: ReaderRouteChildren = {
  ReaderReadingStoryUuidRoute: ReaderReadingStoryUuidRoute,
}

const ReaderRouteWithChildren =
  ReaderRoute._addFileChildren(ReaderRouteChildren)

interface ReadingThemeRouteChildren {
  ReadingThemeReadingThemesKeyRoute: typeof ReadingThemeReadingThemesKeyRoute
}

const ReadingThemeRouteChildren: ReadingThemeRouteChildren = {
  ReadingThemeReadingThemesKeyRoute: ReadingThemeReadingThemesKeyRoute,
}

const ReadingThemeRouteWithChildren = ReadingThemeRoute._addFileChildren(
  ReadingThemeRouteChildren,
)

interface ReviewCardsRouteChildren {
  ReviewCardsReviewCardsRoute: typeof ReviewCardsReviewCardsRoute
}

const ReviewCardsRouteChildren: ReviewCardsRouteChildren = {
  ReviewCardsReviewCardsRoute: ReviewCardsReviewCardsRoute,
}

const ReviewCardsRouteWithChildren = ReviewCardsRoute._addFileChildren(
  ReviewCardsRouteChildren,
)

interface ReviewSessionRouteChildren {
  ReviewSessionReviewSessionRoute: typeof ReviewSessionReviewSessionRoute
}

const ReviewSessionRouteChildren: ReviewSessionRouteChildren = {
  ReviewSessionReviewSessionRoute: ReviewSessionReviewSessionRoute,
}

const ReviewSessionRouteWithChildren = ReviewSessionRoute._addFileChildren(
  ReviewSessionRouteChildren,
)

interface ShellLessonRouteChildren {
  ShellLessonIndexRoute: typeof ShellLessonIndexRoute
}

const ShellLessonRouteChildren: ShellLessonRouteChildren = {
  ShellLessonIndexRoute: ShellLessonIndexRoute,
}

const ShellLessonRouteWithChildren = ShellLessonRoute._addFileChildren(
  ShellLessonRouteChildren,
)

interface ShellReadingRouteChildren {
  ShellReadingGenerateRoute: typeof ShellReadingGenerateRoute
  ShellReadingImportsRoute: typeof ShellReadingImportsRoute
  ShellReadingIndexRoute: typeof ShellReadingIndexRoute
  ShellReadingImportsInstallRoute: typeof ShellReadingImportsInstallRoute
}

const ShellReadingRouteChildren: ShellReadingRouteChildren = {
  ShellReadingGenerateRoute: ShellReadingGenerateRoute,
  ShellReadingImportsRoute: ShellReadingImportsRoute,
  ShellReadingIndexRoute: ShellReadingIndexRoute,
  ShellReadingImportsInstallRoute: ShellReadingImportsInstallRoute,
}

const ShellReadingRouteWithChildren = ShellReadingRoute._addFileChildren(
  ShellReadingRouteChildren,
)

interface ShellReviewRouteChildren {
  ShellReviewPickRoute: typeof ShellReviewPickRoute
  ShellReviewIndexRoute: typeof ShellReviewIndexRoute
}

const ShellReviewRouteChildren: ShellReviewRouteChildren = {
  ShellReviewPickRoute: ShellReviewPickRoute,
  ShellReviewIndexRoute: ShellReviewIndexRoute,
}

const ShellReviewRouteWithChildren = ShellReviewRoute._addFileChildren(
  ShellReviewRouteChildren,
)

interface ShellRouteChildren {
  ShellAccountRoute: typeof ShellAccountRoute
  ShellHomeRoute: typeof ShellHomeRoute
  ShellLessonRoute: typeof ShellLessonRouteWithChildren
  ShellReadingRoute: typeof ShellReadingRouteWithChildren
  ShellReviewRoute: typeof ShellReviewRouteWithChildren
  ShellSearchRoute: typeof ShellSearchRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAccountRoute: ShellAccountRoute,
  ShellHomeRoute: ShellHomeRoute,
  ShellLessonRoute: ShellLessonRouteWithChildren,
  ShellReadingRoute: ShellReadingRouteWithChildren,
  ShellReviewRoute: ShellReviewRouteWithChildren,
  ShellSearchRoute: ShellSearchRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonSessionRoute: LessonSessionRouteWithChildren,
  ReaderRoute: ReaderRouteWithChildren,
  ReadingThemeRoute: ReadingThemeRouteWithChildren,
  ReviewCardsRoute: ReviewCardsRouteWithChildren,
  ReviewSessionRoute: ReviewSessionRouteWithChildren,
  ShellRoute: ShellRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  WordsRoute: WordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
